#!usr/bin/env node

// http://projecteuler.net/problem=2

// Each new term in the Fibonacci sequence is generated by adding 
// he previous two terms. By starting with 1 and 2, the first 10 
// terms will be:
// 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
// By considering the terms in the Fibonacci sequence whose values 
// not exceed four million, find the sum of the even-valued terms.

var isEven = function(a){
	return (a%2 === 0);
}

var sumOfEven = function(arr){
	var sum = 0;
	for (var i in arr){
		if (isEven(arr[i])){
			sum += arr[i];
		}
	}
	return sum;
}
var result = [];

var recursiveForm = function(start, prev, max){

	console.log("count for " + start + ", " + prev + ", " + max);
	result.push(start);
	var curNum = start + prev;
	if (curNum < max) {
		return arguments.callee(curNum, start, max);
	} else {
		return result;
	}	
};

var max = 4000000;
var finalArray = recursiveForm(1,1,max);
console.log(finalArray);
console.log(sumOfEven(finalArray));